<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>The Daily Rage</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <link rel="stylesheet" type="text/css" href="/assets/css/social-sprites.css">
        <link rel="stylesheet" type="text/css" href="/assets/css/animate.css">
        <link rel="stylesheet" type="text/css" href="/assets/css/baguetteBox.min.css">
        <script src="/assets/js/baguetteBox.min.js"></script>
        <!-- main css -->
        <link rel="stylesheet" type="text/css" href="/assets/css/main.css?v=0.4">
    </head>
    <body>
        <div id="latest" style="display:none">0</div>
        <header>
            <a href="/"><div id="logo"></div></a>
            <div id="line"></div>
            <div id="buttons-menu">
              <div class="button">UPLOAD</div>
            </div>
        </header>
        <section id="container"></section>
        <div id="loading"><img src="/assets/img/rolling.svg"></div>
        <footer>
            The Daily Rage © | <a href="/policy">Policy</a>
        </footer>

        <script>

            function debounce(func, wait, immediate) { var timeout; return function() { var context = this, args = arguments; clearTimeout(timeout); timeout = setTimeout(function() { timeout = null; if (!immediate) func.apply(context, args); }, wait); if (immediate && !timeout) func.apply(context, args); }; };

            // define main container
            var container = document.getElementById('container');

            // on page load, retrieve articles [starting_id, key]
            retrieveArticles('0', 'key');

            // on bottom reached, retrieve more articles [starting_id, key]
            scrollAction = debounce(function() {
                if ( (window.innerHeight + window.scrollY) >= document.body.offsetHeight - 100) {
                    // get latest id
                    var latest = document.getElementById("latest").innerHTML;
                    if (latest !== '0' && latest != 'end') {
                        //document.getElementById("loading").innerHTML = '<img src="/assets/img/rolling.svg">';
                        retrieveArticles(latest, 'key');
                    }
                }
            }, 160);

            window.addEventListener('scroll', scrollAction);

            function retrieveArticles(starting_id, key) {
                var xhr = new XMLHttpRequest();
                xhr.open("GET", '/api/take/'+starting_id+'/'+key, true);
                xhr.onreadystatechange = function () {
                    var DONE = 4, // request is done
                        OK = 200; // successful return
                    if (xhr.readyState === DONE) {
                        if (xhr.status === OK) {
                            // JSON parse
                            var articles = JSON.parse(xhr.responseText);
                            // if there are remaining articles
                            if (articles !== "") {
                                // update latest id
                                document.getElementById("latest").innerHTML = articles[articles.length -1].id;
                                // render articles and append to container
                                renderArticles(articles, container);
                                // run gallery if not mobile
                                if (typeof window.orientation == 'undefined') {
                                    baguetteBox.run('#container', {
                                        'animation' : 'fadeIn',
                                        'captions' : false
                                    });
                                }
                            } else {
                                // update latest id as 'end'
                                document.getElementById("latest").innerHTML = 'end';
                                // remove loading image
                                document.getElementById("loading").innerHTML = '';
                                // render no more articles message
                                renderNoMoreArticles(container);
                            }
                        } else {
                            console.log('Error: ' + xhr.status); // An error occurred during the request.
                        }
                    }
                };
                xhr.send(null);
            }

            function renderArticles(articles, container) {
                // console.log($data);
                for (var i = 0; i < articles.length; i++) {

                    var article = document.createElement('article');
                    article.className = 'article animated fadeInUp';
                    name = articles[i].name;
                    picture = articles[i].picture;
                    type = articles[i].type;

                    article.innerHTML = '\
                    <div class="post">\
                        <a href="/assets/posts/'+picture+'" data-caption="Image caption">\
                            <img src="/assets/posts/'+picture+'" alt="Alt Text"/>\
                        </a>\
                    </div>\
                    <div class="meta" type="'+type+'">\
                        <div class="name">\
                            <span class="first-name">'+name+'</span>\
                        </div>\
                        <div class="ss ss-'+type+'"></div>\
                    </div>';
                    container.appendChild(article);
                }
            }

            function renderNoMoreArticles(container) {
                // create new P alement
                var noMore = document.createElement('p');
                // insert content
                noMore.innerHTML = 'No more posts to show';
                // append to container
                container.appendChild(noMore);
            }

        </script>
    </body>
</html>