<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>The Daily Rage</title>
        <link rel="stylesheet" type="text/css" href="/assets/css/social-sprites.css">
        <link rel="stylesheet" type="text/css" href="/assets/css/main.css">
    </head>
    <body>
        <header>
            <div id="logo"></div>
        </header>
        <section class="container">
            <!-- Start Article -->
            <article>
                <div class="post">
                    <img src="/assets/posts/test-1.png"/> <!-- Post img content -->
                </div>
                <div class="meta" type="facebook">
                    <div class="name"> 
                        <span class="first-name">Icaro</span>
                        <span class="second-name">Tealdi</span>
                    </div>
                    <div class="ss ss-facebook"></div>
                </div>
            </article>
            <!-- End Article -->
            <!-- Start Article -->
            <article>
                <div class="post">
                    <img src="/assets/posts/test-2.png"/> <!-- Post img content -->
                </div>
                <div class="meta" type="twitter">
                    <div class="name"> 
                        <span class="first-name">Walter</span>
                        <span class="second-name">Ferrari</span>
                    </div>
                    <div class="ss ss-twitter"></div>
                </div>
            </article>
            <!-- End Article -->
            <!-- Start Article -->
            <article>
                <div class="post">
                    <img src="/assets/posts/test-3.png"/> <!-- Post img content -->
                </div>
                <div class="meta" type="email">
                    <div class="name"> 
                        <span class="first-name">Mia</span>
                        <span class="second-name">Madre</span>
                    </div>
                    <div class="ss ss-email"></div>
                </div>
            </article>
            <!-- End Article -->
            <!-- Start Article -->
            <article>
                <div class="post">
                    <img src="/assets/posts/test-4.png"/> <!-- Post img content -->
                </div>
                <div class="meta" type="youtube">
                    <div class="name"> 
                        <span class="first-name">[attenzione]</span>
                        <span class="second-name">su Google abbiamo un nome utente, non per forza nome+cognome</span>
                    </div>
                    <div class="ss ss-youtube"></div>
                </div>
            </article>
            <!-- End Article -->
        </section>
    </body>
</html>
